---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        systemd_exporter_local_cache_path: "/tmp/systemd_exporter-linux-amd64"
        systemd_exporter_web_listen_address: "127.0.0.1:9000"
        systemd_exporter_version: 0.5.0
        systemd_exporter_tls_server_config:
          cert_file: /etc/systemd_exporter/tls.cert
          key_file: /etc/systemd_exporter/tls.key
        systemd_exporter_enable_file_descriptor_size: true
        systemd_exporter_binary_url: "https://github.com/prometheus-community/systemd_exporter/releases/download/v{{\
                                      \ systemd_exporter_version }}/systemd_exporter-{{ systemd_exporter_version\
                                      \ }}.linux-amd64.tar.gz"
