---
- name: Развертывание инфраструктуры курсового проекта
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - fops39_skv_2025

- name: Установка Prometheus и Node Exporter
  import_playbook: prometheus_server.yaml
  when: install_prometheus | bool

- name: Установка Grafana
  import_playbook: grafana_server.yaml
  when: install_grafana | bool