---
- name: Установка Grafana
  hosts: grafana
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: скачивание Grafana DEB пакета
      get_url:
        url: "{{ grafana_deb_url }}"
        dest: "/tmp/{{ grafana_deb_file }}"
        mode: '0644'
        timeout: 300
        headers:
          Content-Disposition: "attachment"

    - name: Установка Grafana из DEB пакета
      apt:
        deb: "/tmp/{{ grafana_deb_file }}"
        state: present

  roles:
    - grafana.grafana.grafana
