[all:vars]
ansible_user=skv
ansible_ssh_private_key_file="~/.ssh/id_cours_fops39_2025_ed25519"
    
[alb]
158.160.196.209
    
[bastion]
158.160.206.8
    
[webservers]
10.10.10.201 hostname=web-a
10.10.10.211 hostname=web-b
    
[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -o StrictHostKeyChecking=accept-new -W %h:%p -i ~/.ssh/id_cours_fops39_2025_ed25519 skv@158.160.206.8"'
    
[monitoring]
10.10.10.231 hostname=prometheus
10.10.10.232 hostname=grafana
    
[monitoring:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -o StrictHostKeyChecking=accept-new -W %h:%p -i ~/.ssh/id_cours_fops39_2025_ed25519 skv@158.160.206.8"'
    
[logging]
10.10.10.233 hostname=elasticsearch
10.10.10.234 hostname=kibana
    
[logging:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -o StrictHostKeyChecking=accept-new -W %h:%p -i ~/.ssh/id_cours_fops39_2025_ed25519 skv@158.160.206.8"'
