---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        mysqld_exporter_local_cache_path: "/tmp/mysqld_exporter-linux-amd64"
        mysqld_exporter_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        mysqld_exporter_enabled_collectors:
          - slave_hosts
        mysqld_exporter_disabled_collectors:
          - global_variables
        mysqld_exporter_tls_server_config:
          cert_file: /etc/mysqld_exporter/tls.cert
          key_file: /etc/mysqld_exporter/tls.key
        mysqld_exporter_http_server_config:
          http2: true
        mysqld_exporter_basic_auth_users:
          randomuser: examplepassword
        mysqld_exporter_version: 0.15.0
        mysqld_exporter_binary_url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{\
                                     \ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version\
                                     \ }}.linux-amd64.tar.gz"
