---
- name: Копирование манифеста Calico на мастер-ноду
  ansible.builtin.copy:
    src: calico.yaml
    dest: /tmp/calico-manifest.yaml
    mode: '0644'
  when: "'masters' in group_names"
  run_once: true

- name: Применение полного манифеста Calico
  ansible.builtin.command: >
    kubectl apply -f /tmp/calico-manifest.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: "'masters' in group_names"
  run_once: true
  register: k3s_cluster_calico_apply_result
  changed_when: "'created' in k3s_cluster_calico_apply_result.stdout or 'configured' in k3s_cluster_calico_apply_result.stdout"

- name: Ожидание появления подов Calico Node
  ansible.builtin.command: >
    kubectl wait --namespace kube-system -l k8s-app=calico-node --for=condition=Ready pod --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: "'masters' in group_names"
  run_once: true
  changed_when: false
  failed_when: false
  register: k3s_cluster_calico_wait_result
  retries: 2
  delay: 30
  until: k3s_cluster_calico_wait_result.rc == 0

- name: Настройка Calico IPPool (Master)
  when: "'masters' in group_names"
  tags: ['calico', 'network']
  block:
    - name: Удаление дефолтного IPPool
      ansible.builtin.command: >
        kubectl delete ippool default-ipv4-ippool --ignore-not-found=true
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      changed_when: true
      failed_when: false
      run_once: true

    - name: Развертывание манифеста Calico IPPool из шаблона
      ansible.builtin.template:
        src: calico-ippool.yaml.j2
        dest: /tmp/calico-ippool.yaml
        mode: '0644'
      run_once: true

    - name: Применение корректного Calico IPPool
      ansible.builtin.command: >
        kubectl apply -f /tmp/calico-ippool.yaml
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: k3s_cluster_calico_ippool_result
      changed_when: "'created' in k3s_cluster_calico_ippool_result.stdout or 'configured' in k3s_cluster_calico_ippool_result.stdout"
      run_once: true

    - name: Очистка временного файла
      ansible.builtin.file:
        path: /tmp/calico-ippool.yaml
        state: absent
      run_once: true

- name: Применение корректных CIDR — пересоздание подов kube-system
  ansible.builtin.command: >
    kubectl delete pods --all -n kube-system --force --grace-period=0
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: k3s_cluster_pods_reset
  changed_when: true
  failed_when: false
  when: "'masters' in group_names"
  run_once: true

- name: Ожидание готовности узлов кластера после применения IPPool
  ansible.builtin.command: kubectl wait --for=condition=Ready node --all --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: k3s_cluster_nodes_ready
  changed_when: false
  failed_when: false
  when: "'masters' in group_names"
  run_once: true
  retries: 5
  delay: 15
  until: k3s_cluster_nodes_ready.rc == 0
