---
- name: Создание локального каталога .kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false

- name: Получение kubeconfig с master-узла
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "./tmp_kubeconfig_raw"
    flat: true
  when: "'masters' in group_names"
  run_once: true

- name: Замена IP сервера в kubeconfig на IP NLB
  ansible.builtin.replace:
    path: "./tmp_kubeconfig_raw"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443"
  become: false
  delegate_to: localhost
  run_once: true

- name: Перемещение итогового конфига в ~/.kube/config c Принудительной перезаписью
  ansible.builtin.command: mv -f ./tmp_kubeconfig_raw ~/.kube/config
  delegate_to: localhost
  become: false
  changed_when: true
  args:
    removes: ./tmp_kubeconfig_raw
  run_once: true
