---
- name: Создание локального каталога .kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false

- name: Получение kubeconfig с master-узла
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "./tmp_kubeconfig_raw"
    flat: true
  when: "'masters' in group_names"
  run_once: true

- name: Замена IP сервера в kubeconfig на IP NLB
  ansible.builtin.replace:
    path: "./tmp_kubeconfig_raw"
    regexp: 'https://127.0.0.1:{{ k3s_api_port }}'
    replace: "https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:{{ k3s_api_port }}"
  become: false
  delegate_to: localhost
  run_once: true

- name: Перемещение итогового конфига в ~/.kube/config c Принудительной перезаписью
  ansible.builtin.command: mv -f ./tmp_kubeconfig_raw ~/.kube/config
  delegate_to: localhost
  become: false
  changed_when: true
  args:
    removes: ./tmp_kubeconfig_raw
  run_once: true

- name: Вывод информации о доступе к Grafana
  ansible.builtin.debug:
    msg: |
      =================================================================
      Система мониторинга развернута!

      Grafana Dashboard (NodePort {{ grafana_node_port }}, внешний доступ):
      URL: http://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:{{ grafana_node_port }}

      Login: {{ grafana_admin_user }}
      Password: {{ grafana_admin_password }}

      Prometheus UI (ClusterIP, только изнутри кластера):
      kubectl -n {{ monitoring_namespace }} port-forward svc/{{ monitoring_release_name }}-kube-prom-prometheus 9090:9090

      Alertmanager UI (ClusterIP, только изнутри кластера):
      kubectl -n {{ monitoring_namespace }} port-forward svc/{{ monitoring_release_name }}-kube-prom-alertmanager 9093:9093
      =================================================================
  run_once: true
