[all:vars]
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_19-2_ed25519
[prom-core]
93.77.191.134
10.10.10.13 

[node_exp]
10.10.10.12

[node_exp:vars]
ansible_ssh_common_args = '-o ProxyCommand="ssh -p 22 -o StrictHostKeyChecking=accept-new -W %h:%p -q skv@93.77.191.134"'
