---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        chrony_exporter_version: 0.6.0
        chrony_exporter_local_cache_path: "/tmp/chrony_exporter-linux-amd64/{{ chrony_exporter_version }}"
        chrony_exporter_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        chrony_exporter_enabled_collectors:
          - sources
        chrony_exporter_disabled_collectors:
          - tracking
        chrony_exporter_tls_server_config:
          cert_file: /etc/chrony_exporter/tls.cert
          key_file: /etc/chrony_exporter/tls.key
        chrony_exporter_http_server_config:
          http2: true
        chrony_exporter_basic_auth_users:
          randomuser: examplepassword
        chrony_exporter_binary_url: "https://github.com/superq/chrony_exporter/releases/download/v{{ chrony_exporter_version\
                                     \ }}/chrony_exporter-{{ chrony_exporter_version }}.linux-amd64.tar.gz"
