---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        smokeping_prober_local_cache_path: "/tmp/smokeping_prober-linux-amd64"
        smokeping_prober_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        smokeping_prober_tls_server_config:
          cert_file: /etc/smokeping_prober/tls.cert
          key_file: /etc/smokeping_prober/tls.key
        smokeping_prober_http_server_config:
          http2: true
        smokeping_prober_basic_auth_users:
          randomuser: examplepassword
        smokeping_prober_version: 0.7.0
        smokeping_prober_binary_url: "https://github.com/superq/smokeping_prober/releases/download/v{{ smokeping_prober_version\
                                      \ }}/smokeping_prober-{{ smokeping_prober_version }}.linux-amd64.tar.gz"
