[masters]
cl1pe91p5m9cgac980rd-uqan ansible_host=81.26.179.3

[workers]
cl1015remkdroropep9h-ozaz ansible_host=10.10.10.41
cl1015remkdroropep9h-opoc ansible_host=10.10.10.57
cl1015remkdroropep9h-orys ansible_host=10.10.10.29

[workers:vars]
# SSH использовать с ProxyJump в файле ~/.ssh/config_yc_k8s
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_lab22_1_fops40_ed25519

[all:vars]
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_lab22_1_fops40_ed25519