[masters]
cl1k6rbj55uciq502a8d-ezoj ansible_host=51.250.38.106

[workers]
cl1k5hfe7kldnrkfssop-orac ansible_host=10.10.10.26
cl1k5hfe7kldnrkfssop-uher ansible_host=10.10.10.38
cl1k5hfe7kldnrkfssop-onin ansible_host=10.10.10.54

[workers:vars]
# SSH использовать с ProxyJump в файле ~/.ssh/config_yc_k8s
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_lab22_1_fops40_ed25519

[all:vars]
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_lab22_1_fops40_ed25519