[masters]
cl11nsd0cim0jvsf5rn7-ymik ansible_host=158.160.220.212

[workers]
cl13ojsiftc4q3k99uh0-yfuq ansible_host=10.10.10.29
cl13ojsiftc4q3k99uh0-ywis ansible_host=10.10.10.43
cl13ojsiftc4q3k99uh0-yfak ansible_host=10.10.10.56

[workers:vars]
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_lab22_1_fops40_ed25519

[all:vars]
ansible_user=skv
ansible_ssh_private_key_file=~/.ssh/id_lab22_1_fops40_ed25519
