apiVersion: v1
clusters:
- cluster:
    server: https://192.168.89.193:6443
    insecure-skip-tls-verify: true
  name: kind-skv-21-2-k8s-depl
contexts:
- context:
    cluster: kind-skv-21-2-k8s-depl
    user: kind-skv-21-2-k8s-depl
  name: kind-skv-21-2-k8s-depl
current-context: kind-skv-21-2-k8s-depl
kind: Config
users:
- name: kind-skv-21-2-k8s-depl
  user:
    client-certificate-data:
    client-key-data: