# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Путь к ISO образу ALT Linux p11
  altlinux_iso_path_w = "/home/shoel/iso/alt-workstation-11.1-x86_64.iso"
  config.vm.box = "deargle/metasploitable2"
  config.vm.box_version = "0.0.4"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.uri = 'qemu:///system'
    libvirt.memory = 3072
    libvirt.cpus = 2
    libvirt.nested = true
    libvirt.disk_driver :cache => 'none'
    libvirt.disk_bus = "virtio"
    libvirt.nic_model_type = "virtio"
    libvirt.storage :file, :size => '40G', :type => 'qcow2'
    libvirt.management_network_name = "vagrant-libvirt"
    libvirt.management_network_mode = "route"
    libvirt.management_network_guest_ipv6 = "no"
  end
  
  config.vm.define "ub1404" do |ub1404|
    ub1404.vm.hostname = "metasploitable2-ub1404"
    config.ssh.username = 'msfadmin'
    config.ssh.password = 'msfadmin'
    ub1404.vm.network "private_network",
                      libvirt__network_name: "s_private_network", # Имя создаваемой сети
                      libvirt__forward_mode: "none", # Режим маршрутизации
                      libvirt__dhcp_enabled: false  # Отключаем DHCP в этой сети
  end
 # --- Создание ВМ на altlinux ---
  config.vm.define "altlinux_w2" do |node_3|
    # Исправлено: имя хоста должно зависеть от переменной цикла i
    node_3.vm.hostname = "altlinux-w2"
    node_3.vm.communicator = "none"
    # Настройки сети: только private_network
    node_3.vm.network "private_network",
                          libvirt__network_name: "s_private_network",
                          libvirt__forward_mode: "none",
                          libvirt__dhcp_enabled: false

    node_3.vm.provider :libvirt do |libvirt|
      libvirt.boot 'hd' # Загрузка с жесткого диска
      libvirt.boot 'cdrom' # Загрузка с CDROM (вторая опция)
      libvirt.storage :file, :device => :cdrom, :path => altlinux_iso_path_w
      
    end
    node_3.vm.provision "shell", inline: "echo 'altlinux_w2 VM created.'", run: "never"
  end
end