[web]
 skv-develop-web-1   ansible_host=62.84.116.211 fqdn=fhm6n5abaa8mm5q4btrp.auto.internal
 skv-develop-web-2   ansible_host=93.77.185.215 fqdn=fhmjkn5en8njp6q9kkek.auto.internal

[db]
 skv-develop-main   ansible_host=93.77.188.121 fqdn=fhm6fpcf7okfji5igm4d.auto.internal
 skv-develop-replica   ansible_host=10.0.1.35 fqdn=fhm9sldatnjnrs0thsvj.auto.internal

[storage]
 storage   ansible_host=158.160.32.10 fqdn=fhmkf8flraaqsv5gauqp.auto.internal

[all:vars]

ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_lab16_1_fops39_ed25519
