apiVersion: v1
kind: Pod
metadata:
  name: core-k8s
  labels:
    role: den-test-exmpl
    app: my-test-app
    organization: my-test-org
    creator: denskv
spec:
  containers:
    - name: some-name-of-busybox
      image: docker.io/busybox:latest
      command:
        - sleep
        - "3600"
      resources:
        limits:
          memory: "256Mi"
        requests:
          memory: "128Mi"
      ports:
        - name: some-app-port
          containerPort: 80
          protocol: TCP
