---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        postgres_exporter_local_cache_path: "/tmp/postgres_exporter-linux-amd64"
        postgres_exporter_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        postgres_exporter_enabled_collectors:
          - postmaster
        postgres_exporter_disabled_collectors:
          - replication
        postgres_exporter_tls_server_config:
          cert_file: /etc/postgres_exporter/tls.cert
          key_file: /etc/postgres_exporter/tls.key
        postgres_exporter_http_server_config:
          http2: true
        postgres_exporter_basic_auth_users:
          randomuser: examplepassword
        postgres_exporter_version: 0.15.0
        postgres_exporter_binary_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{\
                                       \ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
