apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node-store
  labels:
    role: den-store-exch
    type: hostpath
    organization: netology-fops40
    creator: denskv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: ""
