apiVersion: v1
kind: Service
metadata:
  name: svc-back
  labels:
    role: den-ingress
    app: back-app
    organization: netology-fops40
    creator: denskv
spec:
  type: ClusterIP
  selector:
    app: app-back
  ports:
  - name: http
    port: 1180
    targetPort: 1180
    protocol: TCP
