apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fops-ingress
  labels:
    role: den-ingress
    app: ingress-svc-front-back
    organization: netology-fops40
    creator: denskv
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: contour
  rules:
  - host: fops.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: svc-back
            port:
              number: 8080
      - path: /
        pathType: Exact
        backend:
          service:
            name: svc-front
            port:
              number: 80
