---
clickhouse_users_custom:
      - { name: "skv",
          password: "test1qaz",
          networks: {192.168.89.0/24},
          profile: "default",
          quota: "default",
          dbs: [skvvectordb] ,
          comment: "classic user with multi dbs and multi-custom network allow password"}

clickhouse_listen_host_custom:
  - "192.168.89.104"
...
