---

clickhouse_users_custom:
# - { name: "default", password: "", networks: "{{ clickhouse_networks_default }}", profile: "default", quota: "default", comment: "Default user for login if user not defined" }
  - name: skv
    password: test1qaz
    networks: [192.168.89.113]
    profile: default
    quota: default
    comment: "test-skv"

clickhouse_networks_default:
  - "192.168.89.113"
  - "::1"
  - "127.0.0.1"
...
