---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: git@github.com:shoelacevip12/vector-role.git
    scm: git
    # version: "v0.1"
    name: vector-role

  - src: git@github.com:shoelacevip12/lighthouse-role.git
    scm: git
    # version: "v0.1"
    name: lighthouse-role
