# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = true

  # Общая конфигурация для обеих машин
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20250805.0.0"

  # Конфигурация для libvirt (общая)
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.uri = 'qemu:///system'
    libvirt.memory = 4096
    libvirt.cpus = 2
    libvirt.nested = true
    libvirt.disk_driver :cache => 'none'
    libvirt.disk_bus = "virtio"
    libvirt.default_prefix = "keepalived_"
    libvirt.nic_model_type = "virtio"
    libvirt.management_network_mode = "route"
  end

  # Определение первой машины
  config.vm.define "vrrp1" do |vrrp1|
    vrrp1.vm.hostname = "vrrp1"
    # vrrp1.vm.management_network_address = "192.168.121.3/24"

    vrrp1.vm.cloud_init do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.inline = <<-EOF
        package_update: true
        package_upgrade: true
      EOF
    end

    vrrp1.vm.synced_folder ".",  "/usr/local/bin",
      type: "rsync",
      rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "--include=check_web_server.sh", "--exclude=*"],
      create: true

    vrrp1.vm.synced_folder ".",  "/etc/keepalived",
      type: "rsync",
      rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "--include=keepalived-nginx.conf", "--exclude=*"],
      create: true

    vrrp1.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      sudo systemctl enable --now cloud-init
      sudo cloud-init init
      sudo cloud-init clean
      sudo apt update -y
      sudo apt install -y \
      curl \
      openssh-server \
      libsnmp-base \
      ipvsadm \
      libsnmp40t64 \
      curl \
      ca-certificates \
      nginx \
      nano \
      apt-transport-https \
      gnupg \
      keepalived \
      ncat
      sudo chmod +x /usr/local/bin/check_web_server.sh
      ip_address=$(ip route get 77.88.8.8 2>/dev/null | awk '{print $7; exit}')
      sudo sed -i -e "12s/nginx\!/$ip_address/" /var/www/html/index.nginx-debian.html
      sudo systemctl enable --now nginx.service
      ip_int=$(ip a | grep "2: " | cut -c4-7)
      sudo mv /etc/keepalived/keepalived{-nginx,}.conf
      sudo sed -i -e "9s|ens33|$ip_int|" /etc/keepalived/keepalived.conf
      sudo systemctl enable --now keepalived.service
    SHELL
  end

  # Определение второй машины
  config.vm.define "vrrp2" do |vrrp2|
    vrrp2.vm.hostname = "vrrp2"
    # vrrp2.vm.management_network_address = "192.168.121.4/24"

    vrrp2.vm.cloud_init do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.inline = <<-EOF
        package_update: true
        package_upgrade: true
      EOF
    end

    vrrp2.vm.synced_folder ".",  "/usr/local/bin",
      type: "rsync",
      rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "--include=check_web_server.sh", "--exclude=*"],
      create: true

    vrrp2.vm.synced_folder ".",  "/etc/keepalived",
      type: "rsync",
      rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "--include=keepalived-nginx.conf", "--exclude=*"],
      create: true

    vrrp2.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      sudo systemctl enable --now cloud-init
      sudo cloud-init init
      sudo cloud-init clean
      sudo apt update -y
      sudo apt install -y \
      curl \
      openssh-server \
      libsnmp-base \
      ipvsadm \
      libsnmp40t64 \
      curl \
      ca-certificates \
      nginx \
      nano \
      apt-transport-https \
      gnupg \
      keepalived \
      ncat
      sudo chmod +x /usr/local/bin/check_web_server.sh
      ip_address=$(ip route get 77.88.8.8 2>/dev/null | awk '{print $7; exit}')
      sudo sed -i -e "12s/nginx\!/$ip_address/" /var/www/html/index.nginx-debian.html
      sudo systemctl enable --now nginx.service
      ip_int=$(ip a | grep "2: " | cut -c4-7)
      sudo mv /etc/keepalived/keepalived{-nginx,}.conf
      sudo sed -i -e "8s|MASTER|BACKUP|" \
      -e "9s|ens33|$ip_int|" \
      -e "11s|255|200|" /etc/keepalived/keepalived.conf
      sudo systemctl enable --now keepalived.service
    SHELL
  end
end