# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_version = "4.3.12"

# Cloud-init конфигурация
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.inline = <<-EOF
      package_update: true
      packages:
        - docker.io
        - docker-compose
        - curl
        - openssh-server
        - ca-certificates
        - tzdata
        - perl
        - libatomic1
        - cloud-guest-utils
        - apt-transport-https
        - gnupg
    EOF
  end

  # Конфигурация для libvirt
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.uri = 'qemu:///system'
    libvirt.memory = 6144
    libvirt.cpus = 2
    libvirt.nested = true
    libvirt.disk_driver :cache => 'none'
    libvirt.disk_bus = "virtio"
    libvirt.nic_model_type = "virtio"
    libvirt.host = "gitlab.localdomain"
end

  # Provisioning скрипт
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update
    sudo apt-get install -y cloud-guest-utils cloud-init
    sudo systemctl enable --now cloud-init
    sudo cloud-init init
    sudo cloud-init clean 
    
    # на всякий, если cloud_init не отработал 
    sudo apt-get install -y docker.io docker-compose curl openssh-server ca-certificates tzdata perl libatomic1 apt-transport-https gnupg
    sudo apt-get install -f -y  # Автоматическое устранение зависимостей

    # --- НАЧАЛО: Добавление GPG-ключа GitLab ---
    KEY_FILE="/tmp/gitlab_gitlab-ee-archive-keyring.gpg"
    curl -fsSL https://packages.gitlab.com/gpg.key > "$KEY_FILE"
    sudo mkdir -p /usr/share/keyrings
    sudo gpg --no-default-keyring --keyring /usr/share/keyrings/gitlab_gitlab-ee-archive-keyring.gpg --import "$KEY_FILE"
    rm -f "$KEY_FILE"
    if sudo gpg --no-default-keyring --keyring /usr/share/keyrings/gitlab_gitlab-ee-archive-keyring.gpg --list-keys | grep -q "GitLab B.V."; then
    echo "Ключ GitLab успешно добавлен"
    fi
    # --- КОНЕЦ: Добавление GPG-ключа GitLab ---
    
    # Копирование пакета GitLab
    wget --content-disposition -nv -P /tmp \
    "https://drive.usercontent.google.com/download?id=1ploMBYuV8WBmvV7Lc6Ngy7BeXYPR0N4P&export=download&authuser=0&confirm=t&uuid=b881086c-f5e0-4517-833f-543271291319&at=AN8xHor2sWJTj35mIU3f5GnYGSUK:1753642183746"


    # Установка GitLab
    curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
    sudo apt-get update
    sudo dpkg -i /tmp/gitlab-ee_18.0.5-ee.0_amd64.deb
   
    # Очистка временных файлов
    sudo rm -f /tmp/gitlab-ee_18.0.5-ee.0_amd64.deb
    
    # Дальнейшие настройки
    sudo usermod -aG docker vagrant 
    sudo systemctl enable --now docker
        
    # Загрузка Docker образов
    sudo docker pull gitlab/gitlab-runner:latest
    sudo docker pull docker:latest
    sudo docker pull sonarsource/sonar-scanner-cli:latest
    sudo docker pull golang:1.17

    # Настройка ядра
    sudo sysctl vm.max_map_count=262144
    sudo sysctl -p

    # Обновление hosts файла
    ip_address=$(ip route get 77.88.8.8 2>/dev/null | awk '{print $7; exit}')
    echo -e "$ip_address\tubuntu-focal\tubuntu-focal" >> /etc/hosts
    echo -e "$ip_address\tgitlab.localdomain\tgitlab" >> /etc/hosts
  SHELL
end