# Хост для управления libvirt
[libvirt_host]
localhost ansible_connection=local ansible_user=shoel

[containers]
clickhouse
vector
lighthouse

[containers:vars]
ansible_connection=libvirt_lxc
ansible_libvirt_uri=lxc:///
ansible_user=root

[all:vars]
ansible_python_interpreter=/usr/bin/python3