input {
  beats {
    port => 5044
  }
}

filter {
  # Обработка логов Nginx
  if [service] == "nginx_access" {
    grok {
      match => { "message" => '%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:http_method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}" %{NUMBER:response_code:int} %{NUMBER:bytes_sent:int} "%{GREEDYDATA:referrer}" "%{GREEDYDATA:user_agent}" "%{GREEDYDATA:other}"' }
    }

    date {
      match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }

    useragent {
      source => "user_agent"
      target => "user_agent_details"
    }
    # Добавление тега для идентификации
    mutate {
        add_tag => [ "nginx_log" ]
    }
  }
  # Обработка логов Python по имени контейнера
  else if [container][name] == "some_app" {
    # ВСЕГДА добавлять тег python_log для логов этого контейнера
    mutate {
        add_tag => [ "python_log" ]
    }
    grok {
      # Паттерн: (УРОВЕНЬ):(ИМЯ_ЛОГГЕРА):(СООБЩЕНИЕ)
      match => { "message" => "^%{LOGLEVEL:log_level}:%{DATA:logger_name}:%{GREEDYDATA:log_message_original}$" }
      tag_on_failure => [ "_grokparsefailure_python" ]
    }
    # Извлечение уровеня и сообщения отработки grok 
    if [log_message_original] {
        mutate {
           copy => { "log_message_original" => "[log][message]" }
        }
    } else {
        # Если grok не сработал, копировать оригинальное сообщение
        mutate {
           copy => { "message" => "[log][message]" }
        }
    }
    if [log_level] {
        mutate {
           copy => { "log_level" => "[log][level]" }
        }
    }
  }
}

output {
  # Вывод для логов Nginx
  if "nginx_log" in [tags] {
    stdout {
      codec => rubydebug
    }
    elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "logs_nginx_access-%{+YYYY.MM.dd}"
    }
  }
  # Вывод для логов Python
  else if "python_log" in [tags] {
    stdout {
      codec => rubydebug
    }
    elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "logs_python_gen-%{+YYYY.MM.dd}"
    }
  }
  # вывод для логов, которые не попали ни под одно условие
  else {
    stdout {
      codec => rubydebug
    }
  }
}