version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    # volumes:
    #   - ./deploy/esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.14.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

  logstash:
    image: logstash:8.14.3
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
    depends_on:
          - elasticsearch
    
  filebeat:
    image: elastic/filebeat:8.14.3
    volumes:
      - ./app:/var/log/app/:ro
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
      - elasticsearch
      - kibana


  app:
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: app/Dockerfile.dev
