version: "3.9"
services:
  logstash:
    image: logstash:8.14.3
    environment:
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines

