---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        cadvisor_port: "8000"
        cadvisor_version: 0.47.0
        cadvisor_enable_metrics:
          - tcp
          - memory
          - network
          - cpu
        cadvisor_docker_only: true
        whitelisted_container_labels: [ "com.docker.compose.image" ]
        env_metadata_whitelist: [ "PATH" ]
        store_container_labels: false
