---
# Токен кластера (перенесен в ./group_vars/all/vault )
# k3s_token: "DiplomK8sFops40Token2026!"

# Версии
# k3s_version: "v1.37.0+k3s1"
# helm_version: "v4.3.0"
# CNI_version: "v1.9.1"

# Сетевые настройки
cluster_cidr: "10.20.0.0/16"
service_cidr: "10.21.0.0/16"

# Отключаемые компоненты K3s
k3s_disable_components:
  - traefik
  - servicelb
  - metrics-server
  - flannel
