---
# Токен кластера (перенесен в ./group_vars/all/vault )
# k3s_token: "DiplomK8sFops40Token2026!"

# Версии
# k3s_version: "v1.37.0+k3s1"
# helm_version: "v4.3.0"
# CNI_version: "v1.9.1"

# Сетевые настройки
cluster_cidr: "10.20.0.0/16"
service_cidr: "10.21.0.0/16"

# Отключаемые компоненты K3s
k3s_disable_components:
  - traefik
  - servicelb
  - metrics-server
  - flannel

# Настройки мониторинга
monitoring_namespace: "monitoring"
monitoring_release_name: "prometheus-stack"
monitoring_chart_version: "" # Пусто = последняя версия, или конкретная как пример - "62.5.0"

# Доступ к Grafana через NodePort
grafana_service_type: "NodePort"
grafana_node_port: 30080
grafana_admin_user: "admin"

grafana_admin_password: "DiplomGrafana2026!"