---
# - настраиваемые параметры -> ./roles/k3s_cluster/defaults/main.yml
# - константы роли -> ./roles/k3s_cluster/vars/main.yml
#
# Секреты (k3s_token, grafana_admin_user/password)
# зашифрованы в ./group_vars/all/vault
# расшифровываются из ansible.cfg -> vault_password_file = ./va_pa

# Версии
# k3s_version: "v1.37.0+k3s1"
# helm_version: "v4.3.0"
# CNI_version: "v1.9.1"
