---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        pushgateway_local_cache_path: "/tmp/pushgateway-linux-amd64"
        pushgateway_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        pushgateway_tls_server_config:
          cert_file: /etc/pushgateway/tls.cert
          key_file: /etc/pushgateway/tls.key
        pushgateway_http_server_config:
          http2: true
        pushgateway_basic_auth_users:
          randomuser: examplepassword
        pushgateway_version: 1.5.1
        pushgateway_binary_url: "https://github.com/prometheus/pushgateway/releases/download/v{{ pushgateway_version\
                                 \ }}/pushgateway-{{ pushgateway_version }}.linux-amd64.tar.gz"
