# Этап build
FROM python:3.12-slim AS builder
WORKDIR /app
RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"
COPY . .
RUN --mount=type=cache,target=~/.cache/pip pip install -r requirements.txt

# Этап копирования результатов build И запуск
FROM python:3.12-slim AS worker
WORKDIR /app
COPY --from=builder /app/venv ./venv
COPY --from=builder /app/main.py .
EXPOSE 5000
ENV PATH="/app/venv/bin:$PATH"
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]